name: Check PAT Expiry

on:
  schedule:
    - cron: '0 0 * * 1' # Runs weekly on Monday at midnight
  workflow_dispatch:

jobs:
  check-expiry:
    runs-on: ubuntu-latest

    steps:
    - name: Get token expiration date
      run: |
        echo "Checking Personal Access Token expiration..."
        curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
             -H "Accept: application/vnd.github+json" \
             https://api.github.com/user | jq '.created_at'

    - name: Notify if nearing expiry
      run: |
        EXPIRY_DATE=$(curl -H "Authorization: token ${{ secrets.PAT }}" \
                          -H "Accept: application/vnd.github+json" \
                          https://api.github.com/user | jq '.created_at')
        echo "Token created at: $EXPIRY_DATE"
        # Add logic to notify if expiry is approaching
