name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      check-version:
        required: false
        type: boolean
        description: Should versioning be considered before publishing?

jobs:
  publish-via-push:
    if: github.event_name == 'push'
    uses: stgroves/package-registrar/.github/workflows/publish-to-github.yml@main
    with:
      package-name: stgroves/js-utilities
      check-version: true

  publish-manually:
    if: github.event_name == 'workflow_dispatch'
    uses: stgroves/package-registrar/.github/workflows/publish-to-github.yml@main
    with:
      package-name: stgroves/js-utilities
      check-version: ${{ inputs.check-version }}