name: Publish to GitHub Packages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install Dependencies
        run: npm install

      - name: Get Local Version
        id: local_version
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Local version: $VERSION"

      - name: Get Published Version (GitHub Packages)
        id: published_version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: |
          PUBLISHED_VERSION=$(npm view @stgroves/js-utilities version 2>/dev/null || echo "0.0.0")
          echo "PUBLISHED_VERSION=$PUBLISHED_VERSION" >> $GITHUB_ENV
          echo "Published version: $PUBLISHED_VERSION"

      - name: Check Version Differences
        id: check_version
        run: |
          if [ "$VERSION" == "$PUBLISHED_VERSION" ]; then
            echo "SHOULD_PUBLISH=false" >> $GITHUB_ENV
          else
            echo "SHOULD_PUBLISH=true" >> $GITHUB_ENV
          fi

      - name: Build Package
        run: npm run build || echo "No build step"

      - name: Publish to GitHub Packages
        if: env.SHOULD_PUBLISH == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}